### ISSUE TITLE
Issue in step 6

### ISSUE THREAD

**Issue by kangaderoo** [serghov/GolayCode#1]
Hi,
Thanks for the code, but I think there is an issue in step 6
You swapped the concat order between step3 and 5
but the concat order between step 2 and 6 are the same.
`	u = cur.concat(eyeVector(12, i));`	
this should be
`	u = (eyeVector(12, i)).concat(cur);`
for step 6.

**Comment by serghov** [comment]
Yes you are absolutely right!
Fixed it, https://github.com/serghov/GolayCode/commit/520adfc963308419b01fb34902175eeacb6ab1f7
Thanks
